namespace ArtGallery.Services
{
    public class LocalizationService : ILocalizationService
    {
        private readonly Dictionary<string, Dictionary<string, string>> _localizations = new()
        {
            ["ru"] = new Dictionary<string, string>
            {
                ["SiteName"] = "Галерея Искусств",
                ["Home"] = "Главная",
                ["Portfolio"] = "Портфолио",
                ["Shop"] = "Магазин",
                ["About"] = "О художнике",
                ["Contacts"] = "Контакты",
                ["WelcomeTitle"] = "Добро пожаловать в мир искусства",
                ["WelcomeSubtitle"] = "Уникальные картины для вашего интерьера",
                ["ViewPortfolio"] = "Смотреть портфолио",
                ["GoToShop"] = "Перейти в магазин",
                ["FeaturedWorks"] = "Избранные работы",
                ["AllWorks"] = "Все работы",
                ["Categories"] = "Категории",
                ["All"] = "Все",
                ["Landscapes"] = "Пейзажи",
                ["Portraits"] = "Портреты",
                ["Abstract"] = "Абстракция",
                ["StillLife"] = "Натюрморт",
                ["Price"] = "Цена",
                ["AddToCart"] = "В корзину",
                ["Buy"] = "Купить",
                ["Details"] = "Подробнее",
                ["Year"] = "Год",
                ["Size"] = "Размер",
                ["Technique"] = "Техника",
                ["Available"] = "В наличии",
                ["Sold"] = "Продано",
                ["AboutArtist"] = "О художнике",
                ["ArtistBio"] = "Профессиональный художник с многолетним опытом создания уникальных произведений искусства. Каждая картина - это отражение души и видения мира.",
                ["ArtistPhilosophy"] = "Моя философия",
                ["ArtistPhilosophyText"] = "Искусство должно вдохновлять и пробуждать эмоции. Я стремлюсь создавать работы, которые станут частью вашего дома и будут радовать вас каждый день.",
                ["ContactUs"] = "Свяжитесь с нами",
                ["Name"] = "Имя",
                ["Email"] = "Email",
                ["Subject"] = "Тема",
                ["Message"] = "Сообщение",
                ["Send"] = "Отправить",
                ["Address"] = "Адрес",
                ["Phone"] = "Телефон",
                ["WorkingHours"] = "Часы работы",
                ["Cart"] = "Корзина",
                ["Total"] = "Итого",
                ["Checkout"] = "Оформить заказ",
                ["EmptyCart"] = "Корзина пуста",
                ["Remove"] = "Удалить",
                ["Currency"] = "₽",
                ["ThemeLight"] = "Светлая тема",
                ["ThemeDark"] = "Тёмная тема",
                ["Language"] = "Язык",
                ["FollowUs"] = "Мы в соцсетях",
                ["Newsletter"] = "Подписаться на новости",
                ["Subscribe"] = "Подписаться",
                ["Rights"] = "Все права защищены",
                ["MessageSent"] = "Сообщение отправлено!",
                ["OrderSuccess"] = "Заказ успешно оформлен!"
            },
            ["en"] = new Dictionary<string, string>
            {
                ["SiteName"] = "Art Gallery",
                ["Home"] = "Home",
                ["Portfolio"] = "Portfolio",
                ["Shop"] = "Shop",
                ["About"] = "About Artist",
                ["Contacts"] = "Contacts",
                ["WelcomeTitle"] = "Welcome to the World of Art",
                ["WelcomeSubtitle"] = "Unique paintings for your interior",
                ["ViewPortfolio"] = "View Portfolio",
                ["GoToShop"] = "Go to Shop",
                ["FeaturedWorks"] = "Featured Works",
                ["AllWorks"] = "All Works",
                ["Categories"] = "Categories",
                ["All"] = "All",
                ["Landscapes"] = "Landscapes",
                ["Portraits"] = "Portraits",
                ["Abstract"] = "Abstract",
                ["StillLife"] = "Still Life",
                ["Price"] = "Price",
                ["AddToCart"] = "Add to Cart",
                ["Buy"] = "Buy",
                ["Details"] = "Details",
                ["Year"] = "Year",
                ["Size"] = "Size",
                ["Technique"] = "Technique",
                ["Available"] = "Available",
                ["Sold"] = "Sold",
                ["AboutArtist"] = "About the Artist",
                ["ArtistBio"] = "Professional artist with years of experience creating unique works of art. Each painting is a reflection of the soul and vision of the world.",
                ["ArtistPhilosophy"] = "My Philosophy",
                ["ArtistPhilosophyText"] = "Art should inspire and awaken emotions. I strive to create works that will become part of your home and bring you joy every day.",
                ["ContactUs"] = "Contact Us",
                ["Name"] = "Name",
                ["Email"] = "Email",
                ["Subject"] = "Subject",
                ["Message"] = "Message",
                ["Send"] = "Send",
                ["Address"] = "Address",
                ["Phone"] = "Phone",
                ["WorkingHours"] = "Working Hours",
                ["Cart"] = "Cart",
                ["Total"] = "Total",
                ["Checkout"] = "Checkout",
                ["EmptyCart"] = "Cart is empty",
                ["Remove"] = "Remove",
                ["Currency"] = "$",
                ["ThemeLight"] = "Light Theme",
                ["ThemeDark"] = "Dark Theme",
                ["Language"] = "Language",
                ["FollowUs"] = "Follow Us",
                ["Newsletter"] = "Subscribe to Newsletter",
                ["Subscribe"] = "Subscribe",
                ["Rights"] = "All rights reserved",
                ["MessageSent"] = "Message sent!",
                ["OrderSuccess"] = "Order placed successfully!"
            },
            ["uk"] = new Dictionary<string, string>
            {
                ["SiteName"] = "Галерея Мистецтв",
                ["Home"] = "Головна",
                ["Portfolio"] = "Портфоліо",
                ["Shop"] = "Магазин",
                ["About"] = "Про художника",
                ["Contacts"] = "Контакти",
                ["WelcomeTitle"] = "Ласкаво просимо у світ мистецтва",
                ["WelcomeSubtitle"] = "Унікальні картини для вашого інтер'єру",
                ["ViewPortfolio"] = "Переглянути портфоліо",
                ["GoToShop"] = "Перейти до магазину",
                ["FeaturedWorks"] = "Вибрані роботи",
                ["AllWorks"] = "Усі роботи",
                ["Categories"] = "Категорії",
                ["All"] = "Усі",
                ["Landscapes"] = "Пейзажі",
                ["Portraits"] = "Портрети",
                ["Abstract"] = "Абстракція",
                ["StillLife"] = "Натюрморт",
                ["Price"] = "Ціна",
                ["AddToCart"] = "До кошика",
                ["Buy"] = "Купити",
                ["Details"] = "Детальніше",
                ["Year"] = "Рік",
                ["Size"] = "Розмір",
                ["Technique"] = "Техніка",
                ["Available"] = "В наявності",
                ["Sold"] = "Продано",
                ["AboutArtist"] = "Про художника",
                ["ArtistBio"] = "Професійний художник з багаторічним досвідом створення унікальних творів мистецтва. Кожна картина - це відображення душі та бачення світу.",
                ["ArtistPhilosophy"] = "Моя філософія",
                ["ArtistPhilosophyText"] = "Мистецтво повинно надихати та пробуджувати емоції. Я прагну створювати роботи, які стануть частиною вашого дому і будуть радувати вас щодня.",
                ["ContactUs"] = "Зв'яжіться з нами",
                ["Name"] = "Ім'я",
                ["Email"] = "Email",
                ["Subject"] = "Тема",
                ["Message"] = "Повідомлення",
                ["Send"] = "Надіслати",
                ["Address"] = "Адреса",
                ["Phone"] = "Телефон",
                ["WorkingHours"] = "Години роботи",
                ["Cart"] = "Кошик",
                ["Total"] = "Разом",
                ["Checkout"] = "Оформити замовлення",
                ["EmptyCart"] = "Кошик порожній",
                ["Remove"] = "Видалити",
                ["Currency"] = "₴",
                ["ThemeLight"] = "Світла тема",
                ["ThemeDark"] = "Темна тема",
                ["Language"] = "Мова",
                ["FollowUs"] = "Ми в соцмережах",
                ["Newsletter"] = "Підписатися на новини",
                ["Subscribe"] = "Підписатися",
                ["Rights"] = "Усі права захищені",
                ["MessageSent"] = "Повідомлення надіслано!",
                ["OrderSuccess"] = "Замовлення успішно оформлено!"
            },
            ["de"] = new Dictionary<string, string>
            {
                ["SiteName"] = "Kunstgalerie",
                ["Home"] = "Startseite",
                ["Portfolio"] = "Portfolio",
                ["Shop"] = "Shop",
                ["About"] = "Über den Künstler",
                ["Contacts"] = "Kontakt",
                ["WelcomeTitle"] = "Willkommen in der Welt der Kunst",
                ["WelcomeSubtitle"] = "Einzigartige Gemälde für Ihr Interieur",
                ["ViewPortfolio"] = "Portfolio ansehen",
                ["GoToShop"] = "Zum Shop",
                ["FeaturedWorks"] = "Ausgewählte Werke",
                ["AllWorks"] = "Alle Werke",
                ["Categories"] = "Kategorien",
                ["All"] = "Alle",
                ["Landscapes"] = "Landschaften",
                ["Portraits"] = "Porträts",
                ["Abstract"] = "Abstrakt",
                ["StillLife"] = "Stillleben",
                ["Price"] = "Preis",
                ["AddToCart"] = "In den Warenkorb",
                ["Buy"] = "Kaufen",
                ["Details"] = "Details",
                ["Year"] = "Jahr",
                ["Size"] = "Größe",
                ["Technique"] = "Technik",
                ["Available"] = "Verfügbar",
                ["Sold"] = "Verkauft",
                ["AboutArtist"] = "Über den Künstler",
                ["ArtistBio"] = "Professioneller Künstler mit langjähriger Erfahrung in der Schaffung einzigartiger Kunstwerke. Jedes Gemälde ist ein Spiegel der Seele und der Sicht auf die Welt.",
                ["ArtistPhilosophy"] = "Meine Philosophie",
                ["ArtistPhilosophyText"] = "Kunst soll inspirieren und Emotionen wecken. Ich möchte Werke schaffen, die Teil Ihres Zuhauses werden und Ihnen jeden Tag Freude bereiten.",
                ["ContactUs"] = "Kontaktieren Sie uns",
                ["Name"] = "Name",
                ["Email"] = "E-Mail",
                ["Subject"] = "Betreff",
                ["Message"] = "Nachricht",
                ["Send"] = "Senden",
                ["Address"] = "Adresse",
                ["Phone"] = "Telefon",
                ["WorkingHours"] = "Öffnungszeiten",
                ["Cart"] = "Warenkorb",
                ["Total"] = "Gesamt",
                ["Checkout"] = "Zur Kasse",
                ["EmptyCart"] = "Warenkorb ist leer",
                ["Remove"] = "Entfernen",
                ["Currency"] = "€",
                ["ThemeLight"] = "Helles Theme",
                ["ThemeDark"] = "Dunkles Theme",
                ["Language"] = "Sprache",
                ["FollowUs"] = "Folgen Sie uns",
                ["Newsletter"] = "Newsletter abonnieren",
                ["Subscribe"] = "Abonnieren",
                ["Rights"] = "Alle Rechte vorbehalten",
                ["MessageSent"] = "Nachricht gesendet!",
                ["OrderSuccess"] = "Bestellung erfolgreich aufgegeben!"
            }
        };

        public string Get(string key, string culture)
        {
            if (_localizations.TryGetValue(culture, out var dict))
            {
                if (dict.TryGetValue(key, out var value))
                {
                    return value;
                }
            }
            // Fallback to Russian
            if (_localizations["ru"].TryGetValue(key, out var fallback))
            {
                return fallback;
            }
            return key;
        }

        public Dictionary<string, string> GetAll(string culture)
        {
            return _localizations.TryGetValue(culture, out var dict) ? dict : _localizations["ru"];
        }
    }
}
